services:

  #NODE

  node_container:
    build:
      context: .
      dockerfile: docker/node22-web/Dockerfile.dev
    env_file: .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: unless-stopped
    environment:
      - NODE_PORT=3000
    expose:
      - ${NODE_PORT}
    networks:
      - app-network
    depends_on:
      - postgres_container

  #NGINX

  nginx_container:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "${PORT}:80"
    volumes:
      - ./public:/var/www/public
    depends_on:
      - node_container
    networks:
      - app-network

  #POSTGRES

  postgres_container:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      app-network:
        aliases:
          - ${POSTGRES_HOST}


#OTHERS

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  node_modules: